### ISSUE TITLE
Issue with In(4) 

### ISSUE THREAD

**Issue by ChrisMilojevic** [nicknochnack/OpenCV-Basics#1]
I was walking through the code and when I try to run step 4 I get the following error 

[ WARN:0@0.010] global D:\a\opencv-python\opencv-python\opencv\modules\core\src\utils\samples.cpp (61) cv::samples::findFile cv::samples::findFile('lena.jpg') => 'C:\Users\cmilo\OpenCV\opencv-4.5.5\samples\python/../..\samples/data\lena.jpg'
Traceback (most recent call last):
  File "C:\Users\cmilo\OpenCV\opencv-4.5.5\samples\python\hist.py", line 124, in <module>
    main()
  File "C:\Users\cmilo\OpenCV\opencv-4.5.5\samples\python\hist.py", line 84, in main
    cv.imshow('image',im)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1268: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

I am very new to this so parsing this is beyond me.

**Comment by Meenu00615** [comment]
I'm also getting the same error. it's showing their is no such directory.
command: !cd opencv-4.5.4/samples/python & python hist.py
Error:  /bin/bash: line 1: cd: opencv-4.5.4/samples/python: No such file or directory
          python3: can't open file '/content/hist.py': [Errno 2] No such file or directory
